/** Shared mutable Front Desk state */
export const crm = {
  token: '',
  isMasterPin: false,
  bookings: [],
  guestMessages: [],
  currentFilter: 'settings',
  bookingCallFilter: 'all',
  manualAvailability: { rooms: [], overrides: {} },
  manualSelectedRoom: '',
  availabilityYear: new Date().getFullYear(),
  availabilityMonth: new Date().getMonth(),
  availabilityEditingDay: '',
  availabilityDaySaving: false,
  editingRoomName: '',
  pendingDeleteRoomName: '',
  currentHotelPms: '',
  revenueEnabled: false,
  hotelSubscribed: false,
  revenuePeriod: '30d',
  revenueCache: {},
  revenueLoading: false,
  revenueError: '',
  blockedDemand: { total: 0, today: 0, recent: [] },
  bookingsSubview: 'bookings',
  launchStatus: null,
  growthFunnel: null,
  growthChecklist: {},
  growthPeriod: '30d',
  ALLOWED_REVENUE_PERIODS: new Set(['today', '7d', '30d', 'all']),
  OTA_COMMISSION_RATE: 0.25,
  activeHotelId: '',
  activeHotelName: '',
  activeHotelAppIcon: '',
  appsViewPlatform: 'ios',
  activeHotelDomain: '',
  activeHotelContext: null,
  settingsTourActive: false,
  bootInFlight: false,
  CRM_HOTEL_BY_HOST: {
    'guestlodgeminot.clickinns.com': 'guest-lodge-minot',
    'booking-kappa-nine.vercel.app': 'guest-lodge-minot',
    'stcroix.clickinns.com': 'st-croix-wisconsin',
    'homeplacesuites.clickinns.com': 'home-place-suites',
    'myhomeplacesuites.com': 'home-place-suites',
    'www.myhomeplacesuites.com': 'home-place-suites',
    'suitestay.clickinns.com': 'suite-stay',
    'clickinns.com': 'suite-stay',
    'www.clickinns.com': 'suite-stay',
  },
  CRM_HOTEL_LABELS: {
    'guest-lodge-minot': 'Guest Lodge Minot',
    'st-croix-wisconsin': 'St. Croix Wisconsin',
    'home-place-suites': 'Home Place Suites',
    'suite-stay': 'Suite Stay',
  },
  deferredInstallPrompt: null,
  frontdeskInstalled: false,
  _magicLoginPending: false,
  editRooms: [],
  editRoomsLoadPromise: null,
  messageUnreadCount: 0,
  messagesInboxOpen: false,
  messagesThreadPickerOpen: false,
  selectedMessageThread: '',
  bookingsVirtualList: [],
  bookingsVirtualRaf: 0,
};
